### ISSUE TITLE
Cancel graph renaming on `Escape`

### ISSUE THREAD

**Issue by Ilia-Kosenkov** [kkokosa/dotnet-counters-ui#41]
Right now we confirm the graph panel has been renamed by pressing `Enter`. A natural counterpart would be discarding changes on `Escape`.

**Comment by Ilia-Kosenkov** [comment]
See discussion in #38.

**Comment by v0idzz** [comment]
Actually, #38 should resolve that as well :) Please check the discussion

**Comment by Ilia-Kosenkov** [comment]
I should have double-checked, sorry 😅. Linked this issue so it will be closed once #38 is finished!
